import Foundation

struct Country: Identifiable, Hashable {
  let id = UUID()
  let name: String
  let code: String
  let flag: String
  let dialCode: String

  static func getCurrentCountry() -> Country {
    let locale = Locale.current
    let countryCode = locale.region?.identifier ?? "US"
    return allCountries.first { $0.code == countryCode } ?? allCountries[0]
  }

  static let allCountries: [Country] = [
    Country(name: "Afghanistan", code: "AF", flag: "🇦🇫", dialCode: "+93"),
    Country(name: "Åland Islands", code: "AX", flag: "🇦🇽", dialCode: "+358"),
    Country(name: "Albania", code: "AL", flag: "🇦🇱", dialCode: "+355"),
    Country(name: "Algeria", code: "DZ", flag: "🇩🇿", dialCode: "+213"),
    Country(name: "American Samoa", code: "AS", flag: "🇦🇸", dialCode: "+1"),
    Country(name: "Andorra", code: "AD", flag: "🇦🇩", dialCode: "+376"),
    Country(name: "Angola", code: "AO", flag: "🇦🇴", dialCode: "+244"),
    Country(name: "Anguilla", code: "AI", flag: "🇦🇮", dialCode: "+1"),
    Country(name: "Antarctica", code: "AQ", flag: "🇦🇶", dialCode: "+672"),
    Country(name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬", dialCode: "+1"),
    Country(name: "Argentina", code: "AR", flag: "🇦🇷", dialCode: "+54"),
    Country(name: "Armenia", code: "AM", flag: "🇦🇲", dialCode: "+374"),
    Country(name: "Aruba", code: "AW", flag: "🇦🇼", dialCode: "+297"),
    Country(name: "Australia", code: "AU", flag: "🇦🇺", dialCode: "+61"),
    Country(name: "Austria", code: "AT", flag: "🇦🇹", dialCode: "+43"),
    Country(name: "Azerbaijan", code: "AZ", flag: "🇦🇿", dialCode: "+994"),
    Country(name: "Bahamas", code: "BS", flag: "🇧🇸", dialCode: "+1"),
    Country(name: "Bahrain", code: "BH", flag: "🇧🇭", dialCode: "+973"),
    Country(name: "Bangladesh", code: "BD", flag: "🇧🇩", dialCode: "+880"),
    Country(name: "Barbados", code: "BB", flag: "🇧🇧", dialCode: "+1"),
    Country(name: "Belarus", code: "BY", flag: "🇧🇾", dialCode: "+375"),
    Country(name: "Belgium", code: "BE", flag: "🇧🇪", dialCode: "+32"),
    Country(name: "Belize", code: "BZ", flag: "🇧🇿", dialCode: "+501"),
    Country(name: "Benin", code: "BJ", flag: "🇧🇯", dialCode: "+229"),
    Country(name: "Bermuda", code: "BM", flag: "🇧🇲", dialCode: "+1"),
    Country(name: "Bhutan", code: "BT", flag: "🇧🇹", dialCode: "+975"),
    Country(name: "Bolivia", code: "BO", flag: "🇧🇴", dialCode: "+591"),
    Country(name: "Bonaire, Sint Eustatius and Saba", code: "BQ", flag: "🇧🇶", dialCode: "+599"),
    Country(name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦", dialCode: "+387"),
    Country(name: "Botswana", code: "BW", flag: "🇧🇼", dialCode: "+267"),
    Country(name: "Bouvet Island", code: "BV", flag: "🇧🇻", dialCode: "+47"),
    Country(name: "Brazil", code: "BR", flag: "🇧🇷", dialCode: "+55"),
    Country(name: "British Indian Ocean Territory", code: "IO", flag: "🇮🇴", dialCode: "+246"),
    Country(name: "Brunei Darussalam", code: "BN", flag: "🇧🇳", dialCode: "+673"),
    Country(name: "Bulgaria", code: "BG", flag: "🇧🇬", dialCode: "+359"),
    Country(name: "Burkina Faso", code: "BF", flag: "🇧🇫", dialCode: "+226"),
    Country(name: "Burundi", code: "BI", flag: "🇧🇮", dialCode: "+257"),
    Country(name: "Cabo Verde", code: "CV", flag: "🇨🇻", dialCode: "+238"),
    Country(name: "Cambodia", code: "KH", flag: "🇰🇭", dialCode: "+855"),
    Country(name: "Cameroon", code: "CM", flag: "🇨🇲", dialCode: "+237"),
    Country(name: "Canada", code: "CA", flag: "🇨🇦", dialCode: "+1"),
    Country(name: "Cayman Islands", code: "KY", flag: "🇰🇾", dialCode: "+1"),
    Country(name: "Central African Republic", code: "CF", flag: "🇨🇫", dialCode: "+236"),
    Country(name: "Chad", code: "TD", flag: "🇹🇩", dialCode: "+235"),
    Country(name: "Chile", code: "CL", flag: "🇨🇱", dialCode: "+56"),
    Country(name: "China", code: "CN", flag: "🇨🇳", dialCode: "+86"),
    Country(name: "Christmas Island", code: "CX", flag: "🇨🇽", dialCode: "+61"),
    Country(name: "Cocos (Keeling) Islands", code: "CC", flag: "🇨🇨", dialCode: "+61"),
    Country(name: "Colombia", code: "CO", flag: "🇨🇴", dialCode: "+57"),
    Country(name: "Comoros", code: "KM", flag: "🇰🇲", dialCode: "+269"),
    Country(name: "Congo (Republic)", code: "CG", flag: "🇨🇬", dialCode: "+242"),
    Country(name: "Congo (Dem. Rep.)", code: "CD", flag: "🇨🇩", dialCode: "+243"),
    Country(name: "Cook Islands", code: "CK", flag: "🇨🇰", dialCode: "+682"),
    Country(name: "Costa Rica", code: "CR", flag: "🇨🇷", dialCode: "+506"),
    Country(name: "Croatia", code: "HR", flag: "🇭🇷", dialCode: "+385"),
    Country(name: "Cuba", code: "CU", flag: "🇨🇺", dialCode: "+53"),
    Country(name: "Curaçao", code: "CW", flag: "🇨🇼", dialCode: "+599"),
    Country(name: "Cyprus", code: "CY", flag: "🇨🇾", dialCode: "+357"),
    Country(name: "Czech Republic", code: "CZ", flag: "🇨🇿", dialCode: "+420"),
    Country(name: "Denmark", code: "DK", flag: "🇩🇰", dialCode: "+45"),
    Country(name: "Djibouti", code: "DJ", flag: "🇩🇯", dialCode: "+253"),
    Country(name: "Dominica", code: "DM", flag: "🇩🇲", dialCode: "+1"),
    Country(name: "Dominican Republic", code: "DO", flag: "🇩🇴", dialCode: "+1"),
    Country(name: "Ecuador", code: "EC", flag: "🇪🇨", dialCode: "+593"),
    Country(name: "Egypt", code: "EG", flag: "🇪🇬", dialCode: "+20"),
    Country(name: "El Salvador", code: "SV", flag: "🇸🇻", dialCode: "+503"),
    Country(name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶", dialCode: "+240"),
    Country(name: "Eritrea", code: "ER", flag: "🇪🇷", dialCode: "+291"),
    Country(name: "Estonia", code: "EE", flag: "🇪🇪", dialCode: "+372"),
    Country(name: "Ethiopia", code: "ET", flag: "🇪🇹", dialCode: "+251"),
    Country(name: "Falkland Islands", code: "FK", flag: "🇫🇰", dialCode: "+500"),
    Country(name: "Faroe Islands", code: "FO", flag: "🇫🇴", dialCode: "+298"),
    Country(name: "Fiji", code: "FJ", flag: "🇫🇯", dialCode: "+679"),
    Country(name: "Finland", code: "FI", flag: "🇫🇮", dialCode: "+358"),
    Country(name: "France", code: "FR", flag: "🇫🇷", dialCode: "+33"),
    Country(name: "French Guiana", code: "GF", flag: "🇬🇫", dialCode: "+594"),
    Country(name: "French Polynesia", code: "PF", flag: "🇵🇫", dialCode: "+689"),
    Country(name: "French Southern Territories", code: "TF", flag: "🇹🇫", dialCode: "+262"),
    Country(name: "Gabon", code: "GA", flag: "🇬🇦", dialCode: "+241"),
    Country(name: "Gambia", code: "GM", flag: "🇬🇲", dialCode: "+220"),
    Country(name: "Georgia", code: "GE", flag: "🇬🇪", dialCode: "+995"),
    Country(name: "Germany", code: "DE", flag: "🇩🇪", dialCode: "+49"),
    Country(name: "Ghana", code: "GH", flag: "🇬🇭", dialCode: "+233"),
    Country(name: "Gibraltar", code: "GI", flag: "🇬🇮", dialCode: "+350"),
    Country(name: "Greece", code: "GR", flag: "🇬🇷", dialCode: "+30"),
    Country(name: "Greenland", code: "GL", flag: "🇬🇱", dialCode: "+299"),
    Country(name: "Grenada", code: "GD", flag: "🇬🇩", dialCode: "+1"),
    Country(name: "Guadeloupe", code: "GP", flag: "🇬🇵", dialCode: "+590"),
    Country(name: "Guam", code: "GU", flag: "🇬🇺", dialCode: "+1"),
    Country(name: "Guatemala", code: "GT", flag: "🇬🇹", dialCode: "+502"),
    Country(name: "Guernsey", code: "GG", flag: "🇬🇬", dialCode: "+44"),
    Country(name: "Guinea", code: "GN", flag: "🇬🇳", dialCode: "+224"),
    Country(name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", dialCode: "+245"),
    Country(name: "Guyana", code: "GY", flag: "🇬🇾", dialCode: "+592"),
    Country(name: "Haiti", code: "HT", flag: "🇭🇹", dialCode: "+509"),
    Country(name: "Heard Island and McDonald Islands", code: "HM", flag: "🇭🇲", dialCode: "+ ),"),
    Country(name: "Holy See (Vatican City State)", code: "VA", flag: "🇻🇦", dialCode: "+379"),
    Country(name: "Honduras", code: "HN", flag: "🇭🇳", dialCode: "+504"),
    Country(name: "Hong Kong", code: "HK", flag: "🇭🇰", dialCode: "+852"),
    Country(name: "Hungary", code: "HU", flag: "🇭🇺", dialCode: "+36"),
    Country(name: "Iceland", code: "IS", flag: "🇮🇸", dialCode: "+354"),
    Country(name: "India", code: "IN", flag: "🇮🇳", dialCode: "+91"),
    Country(name: "Indonesia", code: "ID", flag: "🇮🇩", dialCode: "+62"),
    Country(name: "Iran", code: "IR", flag: "🇮🇷", dialCode: "+98"),
    Country(name: "Iraq", code: "IQ", flag: "🇮🇶", dialCode: "+964"),
    Country(name: "Ireland", code: "IE", flag: "🇮🇪", dialCode: "+353"),
    Country(name: "Isle of Man", code: "IM", flag: "🇮🇲", dialCode: "+44"),
    Country(name: "Israel", code: "IL", flag: "🇮🇱", dialCode: "+972"),
    Country(name: "Italy", code: "IT", flag: "🇮🇹", dialCode: "+39"),
    Country(name: "Jamaica", code: "JM", flag: "🇯🇲", dialCode: "+1"),
    Country(name: "Japan", code: "JP", flag: "🇯🇵", dialCode: "+81"),
    Country(name: "Jersey", code: "JE", flag: "🇯🇪", dialCode: "+44"),
    Country(name: "Jordan", code: "JO", flag: "🇯🇴", dialCode: "+962"),
    Country(name: "Kazakhstan", code: "KZ", flag: "🇰🇿", dialCode: "+7"),
    Country(name: "Kenya", code: "KE", flag: "🇰🇪", dialCode: "+254"),
    Country(name: "Kiribati", code: "KI", flag: "🇰🇮", dialCode: "+686"),
    Country(name: "Kuwait", code: "KW", flag: "🇰🇼", dialCode: "+965"),
    Country(name: "Kyrgyzstan", code: "KG", flag: "🇰🇬", dialCode: "+996"),
    Country(name: "Laos", code: "LA", flag: "🇱🇦", dialCode: "+856"),
    Country(name: "Latvia", code: "LV", flag: "🇱🇻", dialCode: "+371"),
    Country(name: "Lebanon", code: "LB", flag: "🇱🇧", dialCode: "+961"),
    Country(name: "Lesotho", code: "LS", flag: "🇱🇸", dialCode: "+266"),
    Country(name: "Liberia", code: "LR", flag: "🇱🇷", dialCode: "+231"),
    Country(name: "Libya", code: "LY", flag: "🇱🇾", dialCode: "+218"),
    Country(name: "Liechtenstein", code: "LI", flag: "🇱🇮", dialCode: "+423"),
    Country(name: "Lithuania", code: "LT", flag: "🇱🇹", dialCode: "+370"),
    Country(name: "Luxembourg", code: "LU", flag: "🇱🇺", dialCode: "+352"),
    Country(name: "Macao", code: "MO", flag: "🇲🇴", dialCode: "+853"),
    Country(name: "North Macedonia", code: "MK", flag: "🇲🇰", dialCode: "+389"),
    Country(name: "Madagascar", code: "MG", flag: "🇲🇬", dialCode: "+261"),
    Country(name: "Malawi", code: "MW", flag: "🇲🇼", dialCode: "+265"),
    Country(name: "Malaysia", code: "MY", flag: "🇲🇾", dialCode: "+60"),
    Country(name: "Maldives", code: "MV", flag: "🇲🇻", dialCode: "+960"),
    Country(name: "Mali", code: "ML", flag: "🇲🇱", dialCode: "+223"),
    Country(name: "Malta", code: "MT", flag: "🇲🇹", dialCode: "+356"),
    Country(name: "Marshall Islands", code: "MH", flag: "🇲🇭", dialCode: "+692"),
    Country(name: "Martinique", code: "MQ", flag: "🇲🇶", dialCode: "+596"),
    Country(name: "Mauritania", code: "MR", flag: "🇲🇷", dialCode: "+222"),
    Country(name: "Mauritius", code: "MU", flag: "🇲🇺", dialCode: "+230"),
    Country(name: "Mayotte", code: "YT", flag: "🇾🇹", dialCode: "+262"),
    Country(name: "Mexico", code: "MX", flag: "🇲🇽", dialCode: "+52"),
    Country(name: "Micronesia", code: "FM", flag: "🇫🇲", dialCode: "+691"),
    Country(name: "Moldova", code: "MD", flag: "🇲🇩", dialCode: "+373"),
    Country(name: "Monaco", code: "MC", flag: "🇲🇨", dialCode: "+377"),
    Country(name: "Mongolia", code: "MN", flag: "🇲🇳", dialCode: "+976"),
    Country(name: "Montenegro", code: "ME", flag: "🇲🇪", dialCode: "+382"),
    Country(name: "Montserrat", code: "MS", flag: "🇲🇸", dialCode: "+1"),
    Country(name: "Morocco", code: "MA", flag: "🇲🇦", dialCode: "+212"),
    Country(name: "Mozambique", code: "MZ", flag: "🇲🇿", dialCode: "+258"),
    Country(name: "Myanmar", code: "MM", flag: "🇲🇲", dialCode: "+95"),
    Country(name: "Namibia", code: "NA", flag: "🇳🇦", dialCode: "+264"),
    Country(name: "Nauru", code: "NR", flag: "🇳🇷", dialCode: "+674"),
    Country(name: "Nepal", code: "NP", flag: "🇳🇵", dialCode: "+977"),
    Country(name: "Netherlands", code: "NL", flag: "🇳🇱", dialCode: "+31"),
    Country(name: "New Caledonia", code: "NC", flag: "🇳🇨", dialCode: "+687"),
    Country(name: "New Zealand", code: "NZ", flag: "🇳🇿", dialCode: "+64"),
    Country(name: "Nicaragua", code: "NI", flag: "🇳🇮", dialCode: "+505"),
    Country(name: "Niger", code: "NE", flag: "🇳🇪", dialCode: "+227"),
    Country(name: "Nigeria", code: "NG", flag: "🇳🇬", dialCode: "+234"),
    Country(name: "Niue", code: "NU", flag: "🇳🇺", dialCode: "+683"),
    Country(name: "Norfolk Island", code: "NF", flag: "🇳🇫", dialCode: "+672"),
    Country(name: "Northern Mariana Islands", code: "MP", flag: "🇲🇵", dialCode: "+1"),
    Country(name: "Norway", code: "NO", flag: "🇳🇴", dialCode: "+47"),
    Country(name: "Oman", code: "OM", flag: "🇴🇲", dialCode: "+968"),
    Country(name: "Pakistan", code: "PK", flag: "🇵🇰", dialCode: "+92"),
    Country(name: "Palau", code: "PW", flag: "🇵🇼", dialCode: "+680"),
    Country(name: "Palestine", code: "PS", flag: "🇵🇸", dialCode: "+970"),
    Country(name: "Panama", code: "PA", flag: "🇵🇦", dialCode: "+507"),
    Country(name: "Papua New Guinea", code: "PG", flag: "🇵🇬", dialCode: "+675"),
    Country(name: "Paraguay", code: "PY", flag: "🇵🇾", dialCode: "+595"),
    Country(name: "Peru", code: "PE", flag: "🇵🇪", dialCode: "+51"),
    Country(name: "Philippines", code: "PH", flag: "🇵🇭", dialCode: "+63"),
    Country(name: "Pitcairn", code: "PN", flag: "🇵🇳", dialCode: "+872"),
    Country(name: "Poland", code: "PL", flag: "🇵🇱", dialCode: "+48"),
    Country(name: "Portugal", code: "PT", flag: "🇵🇹", dialCode: "+351"),
    Country(name: "Puerto Rico", code: "PR", flag: "🇵🇷", dialCode: "+1"),
    Country(name: "Qatar", code: "QA", flag: "🇶🇦", dialCode: "+974"),
    Country(name: "Réunion", code: "RE", flag: "🇷🇪", dialCode: "+262"),
    Country(name: "Romania", code: "RO", flag: "🇷🇴", dialCode: "+40"),
    Country(name: "Russian Federation", code: "RU", flag: "🇷🇺", dialCode: "+7"),
    Country(name: "Rwanda", code: "RW", flag: "🇷🇼", dialCode: "+250"),
    Country(name: "Saint Barthélemy", code: "BL", flag: "🇧🇱", dialCode: "+590"),
    Country(name: "Saint Helena", code: "SH", flag: "🇸🇭", dialCode: "+290"),
    Country(name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳", dialCode: "+1"),
    Country(name: "Saint Lucia", code: "LC", flag: "🇱🇨", dialCode: "+1"),
    Country(name: "Saint Martin", code: "MF", flag: "🇲🇫", dialCode: "+590"),
    Country(name: "Saint Pierre and Miquelon", code: "PM", flag: "🇵🇲", dialCode: "+508"),
    Country(name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨", dialCode: "+1"),
    Country(name: "Samoa", code: "WS", flag: "🇼🇸", dialCode: "+685"),
    Country(name: "San Marino", code: "SM", flag: "🇸🇲", dialCode: "+378"),
    Country(name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹", dialCode: "+239"),
    Country(name: "Saudi Arabia", code: "SA", flag: "🇸🇦", dialCode: "+966"),
    Country(name: "Senegal", code: "SN", flag: "🇸🇳", dialCode: "+221"),
    Country(name: "Serbia", code: "RS", flag: "🇷🇸", dialCode: "+381"),
    Country(name: "Seychelles", code: "SC", flag: "🇸🇨", dialCode: "+248"),
    Country(name: "Sierra Leone", code: "SL", flag: "🇸🇱", dialCode: "+232"),
    Country(name: "Singapore", code: "SG", flag: "🇸🇬", dialCode: "+65"),
    Country(name: "Sint Maarten", code: "SX", flag: "🇸🇽", dialCode: "+1"),
    Country(name: "Slovakia", code: "SK", flag: "🇸🇰", dialCode: "+421"),
    Country(name: "Slovenia", code: "SI", flag: "🇸🇮", dialCode: "+386"),
    Country(name: "Solomon Islands", code: "SB", flag: "🇸🇧", dialCode: "+677"),
    Country(name: "Somalia", code: "SO", flag: "🇸🇴", dialCode: "+252"),
    Country(name: "South Africa", code: "ZA", flag: "🇿🇦", dialCode: "+27"),
    Country(name: "South Georgia & South Sandwich Islands", code: "GS", flag: "🇬🇸", dialCode: "+500"),
    Country(name: "South Sudan", code: "SS", flag: "🇸🇸", dialCode: "+211"),
    Country(name: "Spain", code: "ES", flag: "🇪🇸", dialCode: "+34"),
    Country(name: "Sri Lanka", code: "LK", flag: "🇱🇰", dialCode: "+94"),
    Country(name: "Sudan", code: "SD", flag: "🇸🇩", dialCode: "+249"),
    Country(name: "Suriname", code: "SR", flag: "🇸🇷", dialCode: "+597"),
    Country(name: "Svalbard & Jan Mayen", code: "SJ", flag: "🇸🇯", dialCode: "+47"),
    Country(name: "Sweden", code: "SE", flag: "🇸🇪", dialCode: "+46"),
    Country(name: "Switzerland", code: "CH", flag: "🇨🇭", dialCode: "+41"),
    Country(name: "Syrian Arab Republic", code: "SY", flag: "🇸🇾", dialCode: "+963"),
    Country(name: "Taiwan", code: "TW", flag: "🇹🇼", dialCode: "+886"),
    Country(name: "Tajikistan", code: "TJ", flag: "🇹🇯", dialCode: "+992"),
    Country(name: "Tanzania", code: "TZ", flag: "🇹🇿", dialCode: "+255"),
    Country(name: "Thailand", code: "TH", flag: "🇹🇭", dialCode: "+66"),
    Country(name: "Timor-Leste", code: "TL", flag: "🇹🇱", dialCode: "+670"),
    Country(name: "Togo", code: "TG", flag: "🇹🇬", dialCode: "+228"),
    Country(name: "Tokelau", code: "TK", flag: "🇹🇰", dialCode: "+690"),
    Country(name: "Tonga", code: "TO", flag: "🇹🇴", dialCode: "+676"),
    Country(name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹", dialCode: "+1"),
    Country(name: "Tunisia", code: "TN", flag: "🇹🇳", dialCode: "+216"),
    Country(name: "Turkey", code: "TR", flag: "🇹🇷", dialCode: "+90"),
    Country(name: "Turkmenistan", code: "TM", flag: "🇹🇲", dialCode: "+993"),
    Country(name: "Turks and Caicos Islands", code: "TC", flag: "🇹🇨", dialCode: "+1"),
    Country(name: "Tuvalu", code: "TV", flag: "🇹🇻", dialCode: "+688"),
    Country(name: "Uganda", code: "UG", flag: "🇺🇬", dialCode: "+256"),
    Country(name: "Ukraine", code: "UA", flag: "🇺🇦", dialCode: "+380"),
    Country(name: "United Arab Emirates", code: "AE", flag: "🇦🇪", dialCode: "+971"),
    Country(name: "United Kingdom", code: "GB", flag: "🇬🇧", dialCode: "+44"),
    Country(name: "United States", code: "US", flag: "🇺🇸", dialCode: "+1"),
    Country(name: "Uruguay", code: "UY", flag: "🇺🇾", dialCode: "+598"),
    Country(name: "Uzbekistan", code: "UZ", flag: "🇺🇿", dialCode: "+998"),
    Country(name: "Vanuatu", code: "VU", flag: "🇻🇺", dialCode: "+678"),
    Country(name: "Venezuela", code: "VE", flag: "🇻🇪", dialCode: "+58"),
    Country(name: "Viet Nam", code: "VN", flag: "🇻🇳", dialCode: "+84"),
    Country(name: "Western Sahara", code: "EH", flag: "🇪🇭", dialCode: "+212"),
    Country(name: "Yemen", code: "YE", flag: "🇾🇪", dialCode: "+967"),
    Country(name: "Zambia", code: "ZM", flag: "🇿🇲", dialCode: "+260"),
    Country(name: "Zimbabwe", code: "ZW", flag: "🇿🇼", dialCode: "+263"),
  ]
}
